describe("interfaces", function()
    it("discovery typedef module loads without error", function()
        assert.has_no.errors(function()
            require("neotest-al.discovery")
        end)
    end)

    it("runner typedef module loads without error", function()
        assert.has_no.errors(function()
            require("neotest-al.runner")
        end)
    end)

    it("lsp runner loads without error", function()
        assert.has_no.errors(function()
            require("neotest-al.runner.lsp")
        end)
    end)

    it("lsp runner has build_spec and results functions", function()
        local runner = require("neotest-al.runner.lsp")
        assert.is_function(runner.build_spec)
        assert.is_function(runner.results)
    end)
end)
